name: Build Windows Electron App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Build Windows installer
        run: npm run electron:build
        # Asegúrate de que en package.json tengas definido el script adecuado
        # por ejemplo, "electron:build" o "dist:win" para generar el instalador

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Windows-App
          path: dist/  # Ajusta esta ruta según donde se generen tus archivos de salida
