name: Build Windows Electron App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Update browserslist database
        run: npx update-browserslist-db@latest --force

      - name: Build Windows installer
        run: npm run electron:build
        # Asegúrate de que en package.json el script electron:build realice el build para Windows.

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Windows-App
          path: dist_electron/  # Ajusta según donde se genere el instalador
