name: Build Windows Electron App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      # Agrega el directorio de sdkmanager al PATH
      - name: Add sdkmanager to PATH
        run: echo "C:\Program Files\Android\cmdline-tools\latest\bin" >> $GITHUB_PATH

      - name: Install CMake 3.22.1
        run: sdkmanager --install "cmake;3.22.1"

      - name: Configure CMake dir
        run: echo "cmake.dir=C:\Program Files\Android\sdk\cmake\3.22.1" >> android/gradle.properties

      # Decodificar el keystore antes del build (si es necesario para la firma)
      - name: Decrypt Keystore
        run: |
          echo "$TOM_SP_KEYSTORE_BASE64" | base64 --decode > android/app/tom-SP.keystore
        env:
          TOM_SP_KEYSTORE_BASE64: ${{ secrets.TOM_SP_KEYSTORE_BASE64 }}

      # Configurar propiedades de firma si no están definidas en gradle.properties
      - name: Set up signing properties
        run: |
          echo "MYAPP_UPLOAD_STORE_FILE=tom-SP.keystore" >> android/gradle.properties
          echo "MYAPP_UPLOAD_KEY_ALIAS=${{ secrets.MY_KEY_ALIAS }}" >> android/gradle.properties
          echo "MYAPP_UPLOAD_STORE_PASSWORD=${{ secrets.MY_KEYSTORE_PASSWORD }}" >> android/gradle.properties
          echo "MYAPP_UPLOAD_KEY_PASSWORD=${{ secrets.MY_KEY_PASSWORD }}" >> android/gradle.properties

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle

      - name: Build Release APK
        working-directory: android
        run: |
          chmod +x gradlew
          ./gradlew assembleRelease

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Windows-App
          path: dist/  # Ajusta esta ruta según donde se genere el build
